import { Request, Response, NextFunction } from 'express';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import { prisma } from '../../config/prisma';
import { env } from '../../config/env';
import { sendSuccess, sendError, sendUnauthorized } from '../../utils/response';

export async function login(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { username, password } = req.body as { username: string; password: string };

    const user = await prisma.user.findUnique({
      where: { username: username.toLowerCase().trim() },
    });

    if (!user || !user.isActive) {
      sendUnauthorized(res, 'Invalid username or password');
      return;
    }

    if (user.bannedUntil && new Date(user.bannedUntil) > new Date()) {
      const remaining = Math.ceil((new Date(user.bannedUntil).getTime() - Date.now()) / 60000);
      sendUnauthorized(res, `Account suspended. Try again in ${remaining} minutes.`);
      return;
    }

    const isPasswordValid = await bcrypt.compare(password, user.passwordHash);
    if (!isPasswordValid) {
      sendUnauthorized(res, 'Invalid username or password');
      return;
    }

    // Check for Maintenance Mode (Immunity for SUPER_ADMIN)
    const config = await prisma.systemConfig.findUnique({ where: { id: 1 } });
    if (config?.maintenanceMode && user.role !== 'SUPER_ADMIN') {
      res.status(503).json({
        success: false,
        error: config.maintenanceMessage || 'Server is under maintenance. Only Super Admins can log in right now.',
        maintenance: true
      });
      return;
    }

    // Create session record
    const session = await prisma.session.create({
      data: {
        userId: user.id,
        ipAddress: req.ip,
        userAgent: req.headers['user-agent'] as string,
      }
    });

    const payload = {
      userId: user.id,
      username: user.username,
      role: user.role,
      name: user.name,
      sessionId: session.id, // Added sessionId
    };

    const token = jwt.sign(payload, env.JWT_SECRET, {
      expiresIn: env.JWT_EXPIRES_IN as `${number}${'s'|'m'|'h'|'d'}`,
    });

    sendSuccess(res, {
      token,
      user: {
        id: user.id,
        name: user.name,
        username: user.username,
        role: user.role,
      },
    }, 200, undefined, 'Login successful');
  } catch (err) {
    next(err);
  }
}

export async function getMe(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const user = await prisma.user.findUnique({
      where: { id: req.user!.userId },
      select: {
        id: true,
        name: true,
        username: true,
        role: true,
        isActive: true,
        createdAt: true,
        _count: {
          select: { transactions: true, expenses: true },
        },
      },
    });

    if (!user) {
      sendError(res, 'User not found', 404);
      return;
    }

    // Calculate total contribution (total revenue generated by this user)
    const totalRevenue = await prisma.transaction.aggregate({
      where: { userId: req.user!.userId },
      _sum: { totalPrice: true },
    });

    // Today's stats (IST)
    const today = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Kolkata' });
    const todayStart = new Date(`${today}T00:00:00+05:30`);
    const todayEnd = new Date(`${today}T23:59:59.999+05:30`);

    const todayTransactions = await prisma.transaction.aggregate({
      where: {
        userId: req.user!.userId,
        createdAt: { gte: todayStart, lte: todayEnd },
      },
      _sum: { totalPrice: true },
      _count: true,
    });

    const recentLogs = await prisma.log.findMany({
      where: { userId: req.user!.userId },
      orderBy: { createdAt: 'desc' },
      take: 5,
      select: {
        action: true,
        tableName: true,
        createdAt: true,
      },
    });

    sendSuccess(res, {
      ...user,
      totalRevenue: totalRevenue._sum.totalPrice ?? 0,
      todayStats: {
        transactions: todayTransactions._count,
        revenue: todayTransactions._sum.totalPrice ?? 0,
      },
      recentActivity: recentLogs,
    });
  } catch (err) {
    next(err);
  }
}

export async function changePassword(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { currentPassword, newPassword } = req.body as {
      currentPassword: string;
      newPassword: string;
    };

    const user = await prisma.user.findUnique({
      where: { id: req.user!.userId },
    });

    if (!user) {
      sendError(res, 'User not found', 404);
      return;
    }

    const isValid = await bcrypt.compare(currentPassword, user.passwordHash);
    if (!isValid) {
      sendUnauthorized(res, 'Current password is incorrect');
      return;
    }

    const newHash = await bcrypt.hash(newPassword, 12);
    await prisma.user.update({
      where: { id: user.id },
      data: { passwordHash: newHash },
    });

    sendSuccess(res, null, 200, undefined, 'Password changed successfully');
  } catch (err) {
    next(err);
  }
}
