import React, { useEffect, useState } from 'react';
import Layout from '../../components/layout/Layout';
import { logsApi } from '../../api';
import { Log } from '../../types';

export default function BillLogsPage() {
  const [logs, setLogs] = useState<Log[]>([]);
  const [loading, setLoading] = useState(true);

  // Pagination
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const limit = 50;

  const fetchLogs = () => {
    setLoading(true);
    logsApi.list({ page, limit, tableName: 'bills' })
      .then(res => {
        setLogs(res.data.data ?? []);
        if (res.data.meta && res.data.meta.total) {
          setTotalPages(Math.ceil(res.data.meta.total / limit));
        }
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchLogs();
  }, [page]);

  return (
    <Layout title="Bill Logs">
      <div className="page-header">
        <div>
          <div className="page-header-title">Bill Logs</div>
          <div className="page-header-sub">History of all generated invoices and bills</div>
        </div>
        <button className="btn btn-ghost" onClick={fetchLogs}>🔄 Refresh</button>
      </div>

      <div className="card">
        {loading ? (
          <div className="page-loading"><div className="spinner spinner-lg"></div>Loading bill logs...</div>
        ) : logs.length === 0 ? (
          <div className="empty-state">
            <div className="empty-state-icon">📄</div>
            <div className="empty-state-title">No Bills Generated</div>
            <div className="empty-state-sub">Generated bills will appear here.</div>
          </div>
        ) : (
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>Timestamp</th>
                  <th>Generated By</th>
                  <th>Customer Name</th>
                  <th>Total Amount</th>
                  <th>Bill Details</th>
                </tr>
              </thead>
              <tbody>
                {logs.map(log => {
                  const billData = log.newValue as any;
                  return (
                    <tr key={log.id}>
                      <td style={{ whiteSpace: 'nowrap' }}>{new Date(log.createdAt).toLocaleString()}</td>
                      <td style={{ fontWeight: 600 }}>{log.user.name}</td>
                      <td>{billData?.customerName || 'Walk-in Customer'}</td>
                      <td style={{ fontWeight: 800, color: 'var(--color-accent)' }}>₹{Number(billData?.total || 0).toFixed(2)}</td>
                      <td style={{ fontSize: 12, color: 'var(--text-muted)' }}>
                        {billData?.items?.length} items. Date on bill: {billData?.date}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        {/* Pagination */}
        {totalPages > 1 && (
          <div style={{ display: 'flex', justifyContent: 'center', gap: 10, marginTop: 20 }}>
            <button className="btn btn-ghost btn-sm" disabled={page === 1} onClick={() => setPage(p => p - 1)}>
              ← Previous
            </button>
            <span style={{ fontSize: 13, display: 'flex', alignItems: 'center' }}>
              Page {page} of {totalPages}
            </span>
            <button className="btn btn-ghost btn-sm" disabled={page === totalPages} onClick={() => setPage(p => p + 1)}>
              Next →
            </button>
          </div>
        )}
      </div>
    </Layout>
  );
}
